dist: xenial
language: c

addons:
  apt:
    sources:
      - sourceline: 'deb http://us.archive.ubuntu.com/ubuntu/ trusty universe'
    packages:
      - vera++
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi

install:
  - git clone https://github.com/SpiNNakerManchester/SupportScripts.git support
  - support/gitclone.sh https://github.com/SpiNNakerManchester/spinnaker_tools.git
  - export SPINN_DIRS=`pwd`/spinnaker_tools GNU=1
  - make -C spinnaker_tools/sark
  - make -C spinnaker_tools/spin1_api

script:
  - CFLAGS=-fdiagnostics-color make
  - make install
  - support/run-vera.sh include -P max-file-length=2500
  - support/run-vera.sh src
